In [1]:
print("Hello World!")

Hello World!


In [1]:
import numpy as np

In [5]:
np.random.rand(4)

array([0.91230077, 0.24080212, 0.7073837 , 0.852397  ])

In [6]:
np.random.seed(0)

In [7]:
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [8]:
np.random.rand(4)

array([0.4236548 , 0.64589411, 0.43758721, 0.891773  ])

In [10]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [11]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])